DROP TABLE ONLINE_PERIODICAL;
DROP TABLE ONLINE_EBOOK;
DROP TABLE ONLINE_AUDIO;
DROP TABLE ONLINE_MOVIE;
DROP TABLE PERIODICAL;
DROP TABLE EBOOK;
DROP TABLE AUDIOBOOK;
DROP TABLE MOVIE;
DROP TABLE CHECKOUT;
DROP TABLE BOOK;
DROP TABLE PUBLISHER;
DROP TABLE EMPLOYEE;
DROP TABLE JOB;
DROP TABLE AUTHOR;
DROP TABLE CARDHOLDER;
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/YY';
CREATE TABLE "PUBLISHER" (
  "PUBLISH_ID" number(9),
  "NAME" varchar2(30) NOT NULL,
  PRIMARY KEY ("PUBLISH_ID")
);

CREATE TABLE "JOB" (
  "JOB_ID" number(9),
  "NAME" varchar2(30) NOT NULL,
  "WAGE" number(5,2) NOT NULL CHECK ("WAGE" >= 11.00),
  "MIN_HOURS" number(2) NOT NULL,
  "EDU_REQ" varchar2(100) NOT NULL,
  PRIMARY KEY ("JOB_ID")
);

CREATE TABLE "AUTHOR" (
  "AUTHOR_ID" number(9),
  "FNAME" varchar2(15) NOT NULL,
  "LNAME" varchar2(15) NOT NULL,
  "INIT" varchar2(1),
  PRIMARY KEY ("AUTHOR_ID")
);

CREATE TABLE "CARDHOLDER" (
  "CARD_ID" number(9),
  "DATE_RENEW" date NOT NULL,
  "PIN" number(6) NOT NULL,
  "FEE_DUE" number(5,2),
  "FNAME" varchar2(15) NOT NULL,
  "LNAME" varchar2(15) NOT NULL,
  "ADDRESS" varchar2(30) NOT NULL,
  PRIMARY KEY ("CARD_ID")
);

CREATE TABLE "EMPLOYEE" (
  "EMP_ID" number(9),
  "FNAME" varchar2(15) NOT NULL,
  "LNAME" varchar2(15) NOT NULL,
  "AREACODE" number(3) NOT NULL,
  "PHONE" number(7) NOT NULL,
  "EMAIL" varchar2(30) NOT NULL,
  "ADDRESS" varchar2(30) NOT NULL,
  "JOB_ID" number(9) NOT NULL,
  PRIMARY KEY ("EMP_ID"),
    FOREIGN KEY ("JOB_ID")
      REFERENCES "JOB"("JOB_ID")
);

CREATE TABLE "CHECKOUT" (
  "BOOK_ID" number(9),
  "DATE_DUE" date NOT NULL,
  "DATE_RETURN" date,
  "CARD_ID" number(9) NOT NULL,
  "EMP_ID" number(9) NOT NULL,
  PRIMARY KEY ("BOOK_ID", "DATE_DUE"),
    FOREIGN KEY ("EMP_ID")
      REFERENCES "EMPLOYEE"("EMP_ID"),
    FOREIGN KEY ("CARD_ID")
      REFERENCES "CARDHOLDER"("CARD_ID")
);

CREATE TABLE "PERIODICAL" (
  "PER_ID" number(9),
  "NAME" varchar2(100) NOT NULL,
  "PAGES" number(4),
  "ISSUE" number(4) NOT NULL,
  "DATE_PUBLISH" date,
  "CATEGORY" varchar2(30),
  "PUBLISH_ID" number(9) NOT NULL,
  PRIMARY KEY ("PER_ID"),
    FOREIGN KEY ("PUBLISH_ID")
      REFERENCES "PUBLISHER"("PUBLISH_ID")
);

CREATE TABLE "ONLINE_PERIODICAL" (
  "CARD_ID" number(9),
  "PER_ID" number(9),
  PRIMARY KEY ("CARD_ID", "PER_ID"),
    FOREIGN KEY ("CARD_ID")
      REFERENCES "CARDHOLDER"("CARD_ID"),
    FOREIGN KEY ("PER_ID")
      REFERENCES "PERIODICAL"("PER_ID")
);

CREATE TABLE "EBOOK" (
  "EBOOK_ID" number(9),
  "ISBN" number(13),
  "TITLE" varchar2(100) NOT NULL,
  "PAGES" number(4),
  "CATEGORY" varchar2(30),
  "YEAR" number(4),
  "AUTHOR_ID" number(9) NOT NULL,
  "PUBLISH_ID" number(9) NOT NULL,
  PRIMARY KEY ("EBOOK_ID"),
    FOREIGN KEY ("AUTHOR_ID")
      REFERENCES "AUTHOR"("AUTHOR_ID"),
    FOREIGN KEY ("PUBLISH_ID")
      REFERENCES "PUBLISHER"("PUBLISH_ID")
);

CREATE TABLE "AUDIOBOOK" (
  "AUDIO_ID" number(9),
  "NAME" varchar2(100) NOT NULL,
  "LENGTH" number(3) NOT NULL,
  "CATEGORY" varchar2(30),
  "AUTHOR_ID" number(9) NOT NULL,
  "PUBLISH_ID" number(9) NOT NULL,
  PRIMARY KEY ("AUDIO_ID"),
    FOREIGN KEY ("AUTHOR_ID")
      REFERENCES "AUTHOR"("AUTHOR_ID"),
    FOREIGN KEY ("PUBLISH_ID")
      REFERENCES "PUBLISHER"("PUBLISH_ID")
);

CREATE TABLE "ONLINE_AUDIO" (
  "CARD_ID" number(9),
  "AUDIO_ID" number(9),
  PRIMARY KEY ("CARD_ID", "AUDIO_ID"),
    FOREIGN KEY ("CARD_ID")
      REFERENCES "CARDHOLDER"("CARD_ID"),
    FOREIGN KEY ("AUDIO_ID")
      REFERENCES "AUDIOBOOK"("AUDIO_ID")
);

CREATE TABLE "MOVIE" (
  "MOV_ID" number(9),
  "NAME" varchar2(100) NOT NULL,
  "LENGTH" number(3) NOT NULL,
  "CATEGORY" varchar2(30),
  "PUBLISH_ID" number(9) NOT NULL,
  PRIMARY KEY ("MOV_ID"),
    FOREIGN KEY ("PUBLISH_ID")
      REFERENCES "PUBLISHER"("PUBLISH_ID")
);

CREATE TABLE "ONLINE_MOVIE" (
  "CARD_ID" number(9),
  "MOVIE_ID" number(9),
  PRIMARY KEY ("CARD_ID", "MOVIE_ID"),
    FOREIGN KEY ("CARD_ID")
      REFERENCES "CARDHOLDER"("CARD_ID"),
    FOREIGN KEY ("MOVIE_ID")
      REFERENCES "MOVIE"("MOV_ID")
);

CREATE TABLE "BOOK" (
  "BOOK_ID" number(9),
  "TITLE" varchar2(100) NOT NULL,
  "PAGES" number(4),
  "CATEGORY" varchar2(30),
  "QUALITY" varchar2(2) DEFAULT 'F',
  "YEAR" number(4),
  "ISBN" number(13) NOT NULL,
  "AUTHOR_ID" number(9) NOT NULL,
  "PUBLISH_ID" number(9) NOT NULL,
  PRIMARY KEY ("BOOK_ID"),
    FOREIGN KEY ("PUBLISH_ID")
      REFERENCES "PUBLISHER"("PUBLISH_ID"),
    FOREIGN KEY ("AUTHOR_ID")
      REFERENCES "AUTHOR"("AUTHOR_ID")
);

CREATE TABLE "ONLINE_EBOOK" (
  "CARD_ID" number(9),
  "EBOOK_ID" number(9),
  PRIMARY KEY ("CARD_ID", "EBOOK_ID"),
    FOREIGN KEY ("EBOOK_ID")
      REFERENCES "EBOOK"("EBOOK_ID"),
    FOREIGN KEY ("CARD_ID")
      REFERENCES "CARDHOLDER"("CARD_ID")
);