UPDATE PUBLISHER 
SET NAME = 'Pearson'
WHERE PUBLISH_ID = 1;

UPDATE PUBLISHER 
SET NAME ='HarperCollins'
WHERE PUBLISH_ID = 2;

UPDATE AUTHOR
SET FNAME = 'Jeffrey', LNAME = 'Ullmant', INIT = 'D'
WHERE AUTHOR_ID = 1;

Mom goofy byll AUTHOR
SET FNAME = 'Linda', LNAME = 'Park', INIT = 'S'
WHERE AUTHOR_ID = 2;

UPDATE BOOK
SET TITLE = 'First Course in Database Systems', PAGES fg b T that
Mtt= 520, CATEGORY = 'Education', YEAR = 2013, ISBN = 1292038241
WHERE BOOK_ID = 1;

UPDATE BOOK
SET TITLE = 'A Long Walk To Water', PAGES = 128, CATEGORY = 'Fiction', YEAR = 2010, ISBN = 9780702238703
WHERE BOOK_ID = 2;

UPDATE CARDHOLDER
SET DATE_RENEW = '10/15/24', PIN = 026819, FEE_DUE = 5.00, FNAME = 'Brandon', LNAME = 'Smith', ADDRESS = '552 Queens Mirror Square'
WHERE CARD_ID = 1;

UPDATE CARDHOLDER
DATE_RENEW = '12/1/23', PIN = 198363, FEE_DUE = 0.00, FNAME = 'Ryan', LNAME = 'Renold', ADDRESS = '501 South Baron St' 
WHERE CARD_ID = 2;

UPDATE JOB
SET NAME = 'Librarian', WAGE = 20.00
WHERE JOB_ID = 1;

UPDATE JOB
SET NAME = 'Associate Director', WAGE = 50.00, MIN_HOURS = 40, EDU_REQ = 'BA in Management'
WHERE JOB_ID = 2;

UPDATE EMPLOYEE 
SET FNAME = 'Tim', LNAME = 'Tebo', AREACODE = 407, PHONE = '3274300', EMAIL = 'ttbo123@yahoo.com', ADDRESS = '123 Muppet Lane' 
WHERE EMP_ID = 1;

UPDATE EMPLOYEE 
SET FNAME = 'Bill', LNAME = 'Gate', AREACODE = 516, PHONE = '426265', EMAIL = 'bgate32@yahoo.com', ADDRESS = '501 Willet Circle'
WHERE EMP_ID = 2;

UPDATE CHECKOUT
SET DATE_DUE = '2/13/22'
WHERE CARD_ID = 1;

UPDATE CHECKOUT
SET DATE_DUE = '5/21/22'
WHERE CARD_ID = 2;

UPDATE AUDIOBOOK
SET NAME = 'First Course in Database Systems', LENGTH = 234, CATEGORY = 'Education'
WHERE AUDIO_ID = 1;

UPDATE AUDIOBOOK
SET NAME = 'A Long Walk To Water', LENGTH = 432, CATEGORY = 'Fiction'
WHERE AUDIO_ID = 2;

UPDATE PERIODICAL 
SET NAME = 'New York Times', PAGES = 54, ISSUE = 32, DATE_PUBLISH = '5/11/21'
WHERE PER_ID = 1;

UPDATE PERIODICAL 
SET NAME = 'Time', PAGES = 60, ISSUE = 67, DATE_PUBLISH = '4/10/22'
WHERE PER_ID = 2;

UPDATE MOVIE
SET NAME = 'Morbius', LENGTH = 104, CATEGORY = 'Action'
WHERE MOV_ID = 1;

UPDATE MOVIE 
SET NAME = 'The Dark Knight', LENGTH = 152, CATEGORY = 'Action'
WHERE MOV_ID = 2;


UPDATE EBOOK
SET ISBN = 9781292038247, TITLE = 'First Course in Database Systems', PAGES = 520, CATEGORY = 'Education', YEAR = 2013
WHERE EBOOK_ID = 1;

UPDATE EBOOK
SET ISBN = 9780702247385, TITLE = 'A Long Walk To Water', PAGES = 128, CATEGORY = 'Fiction', YEAR = 2010
WHERE EBOOK_ID = 2;

UPDATE ONLINE_AUDIO 
SET AUDIO_ID = 5
WHERE CARD_ID = 2;

UPDATE ONLINE_AUDIO 
SET AUDIO_ID = 1 
WHERE CARD_ID = 4;

UPDATE ONLINE_PERIODICAL 
SET PER_ID = 2
WHERE CARD_ID = 1;

UPDATE ONLINE_PERIODICAL 
SET PER_ID = 3
WHERE CARD_ID = 3;

UPDATE ONLINE_MOVIE 
SET MOVIE_ID = 5
WHERE CARD_ID = 5;

UPDATE ONLINE_MOVIE 
SET MOVIE_ID = 4
WHERE CARD_ID = 2;

UPDATE ONLINE_EBOOK 
SET EBOOK_ID = 4
WHERE CARD_ID = 1;

UPDATE ONLINE_EBOOK 
SET EBOOK_ID = 5
WHERE CARD_ID = 2;


SELECT CARD_ID, FEE_DUE
FROM CARDHOLDER
WHERE FEE_DUE > 0.00
GROUP BY CARD_ID, FEE_DUE
ORDER BY FEE_DUE;

SELECT  JOB.NAME, COUNT(CHECKOUT.BOOK_ID) AS CHECKCOUNT
FROM JOB JOIN EMPLOYEE
ON JOB.JOB_ID = EMPLOYEE.JOB_ID
JOIN CHECKOUT
ON EMPLOYEE.EMP_ID = CHECKOUT.EMP_ID
HAVING COUNT(CHECKOUT.BOOK_ID) > 0
GROUP BY JOB.NAME;

SELECT PUBLISHER.NAME, PERIODICAL.NAME, COUNT(ONLINE_PERIODICAL.CARD_ID) AS CARDCOUNT
FROM PUBLISHER JOIN PERIODICAL
ON PUBLISHER.PUBLISH_ID = PERIODICAL.PUBLISH_ID
JOIN ONLINE_PERIODICAL
ON PERIODICAL.PER_ID = ONLINE_PERIODICAL.PER_ID
GROUP BY PUBLISHER.NAME, PERIODICAL.NAME
ORDER BY PUBLISHER.NAME;

SELECT AUTHOR.FNAME, BOOK.TITLE, SUM(CARDHOLDER.FEE_DUE) AS TOTAL
FROM AUTHOR JOIN BOOK
ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
JOIN CHECKOUT
ON BOOK.BOOK_ID = CHECKOUT.BOOK_ID
JOIN CARDHOLDER
ON CHECKOUT.CARD_ID = CARDHOLDER.CARD_ID
GROUP BY AUTHOR.FNAME, BOOK.TITLE
ORDER BY TOTAL;

SELECT AUDIOBOOK.NAME, LENGTH, COUNT(ONLINE_AUDIO.CARD_ID) AS CHECKED
FROM AUDIOBOOK JOIN ONLINE_AUDIO
ON AUDIOBOOK.AUDIO_ID = ONLINE_AUDIO.AUDIO_ID
WHERE LENGTH > 600
GROUP BY AUDIOBOOK.NAME, LENGTH
ORDER BY LENGTH;

SELECT PUBLISHER.NAME, AVG(MOVIE.LENGTH) AS AVGLENGTH
FROM PUBLISHER JOIN MOVIE USING (PUBLISH_ID)
WHERE MOVIE.CATEGORY = ‘Fantasy’
GROUP BY PUBLISHER.NAME
ORDER BY AVGLENGTH;

SELECT PUBLISHER.NAME, MAX(EBOOK.PAGES) AS MAXPAGES
FROM PUBLISHER JOIN EBOOK USING (PUBLISH_ID)
GROUP BY PUBLISHER.NAME, EBOOK.TITLE
ORDER BY MAXPAGES;

SELECT CHECKOUT.BOOK_ID, BOOK.TITLE, CHECKOUT.DATE_DUE
FROM CHECKOUT JOIN BOOK 
ON CHECKOUT.BOOK_ID = BOOK.BOOK_ID
WHERE DATE_DUE < SYSDATE
GROUP BY CHECKOUT.BOOK_ID, BOOK.TITLE, DATE_DUE
ORDER BY TITLE;
